# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClassifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('th_meas_min', models.IntegerField(blank=True, null=True)),
                ('th_meas_max', models.IntegerField(blank=True, null=True)),
                ('meas_spec_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year_min', models.IntegerField(blank=True, null=True)),
                ('year_max', models.IntegerField(blank=True, null=True)),
                ('commercial_fee', models.FloatField()),
                ('base_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('measurement', models.CharField(choices=[('cc', 'c.c.'), ('T', 'Toneladas'), ('P', 'Pasajeros'), ('N', 'Ninguna')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='vehicleclassifications',
            name='vehicle_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleType'),
        ),
    ]
