############################################################
# Dockefile for jaconsta python3.5
############################################################

FROM ubuntu:16.04

MAINTAINER  Javier Constain

# Update sources packages
run apt-get update && apt-get upgrade -y
run apt-get install -y python3.5 python3-pip
